name: CI tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Checkout LMDB
        uses: actions/checkout@v7
        with:
          repository: LMDB/lmdb
          path: lmdb
          ref: LMDB_1.0.1
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential
      - name: Build LMDB
        run: |
          cd $GITHUB_WORKSPACE/lmdb/libraries/liblmdb
          make
          sudo make install
      - name: Install roswell
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install qlot
        run: |
          ros install qlot
      - name: Set Path
        run: |
          echo "${HOME}/.roswell/bin" >> $GITHUB_PATH
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          export LD_LIBRARY_PATH=/usr/local/lib
          qlot install
          qlot exec ros -l test/ci.lisp
